"""Candidate policy identities for the additive Swing V1 analytical path."""

SWING_V1_STRUCTURAL_DISCOVERY_POLICY_ID = (
    "SWING-PHASE1-V1-STRUCTURAL-DISCOVERY-POLICY"
)
SWING_V1_PROBABLE_FORMATION_POLICY_ID = (
    "SWING-PHASE1-V1-PROBABLE-FORMATION-POLICY"
)
SWING_V1_VOLUME_EVIDENCE_POLICY_ID = "SWING-PHASE1-V1-VOLUME-EVIDENCE-POLICY"
SWING_V1_CANDLE_EVIDENCE_POLICY_ID = "SWING-PHASE1-V1-CANDLE-EVIDENCE-POLICY"
SWING_V1_VOLATILITY_EVIDENCE_POLICY_ID = (
    "SWING-PHASE1-V1-VOLATILITY-EVIDENCE-POLICY"
)
SWING_V1_FUTURES_POSITIONING_POLICY_ID = (
    "SWING-PHASE1-V1-FUTURES-POSITIONING-POLICY"
)
SWING_V1_IMPULSE_MATURITY_POLICY_ID = (
    "SWING-PHASE1-V1-IMPULSE-MATURITY-POLICY"
)
SWING_V1_RELATIVE_CONTEXT_POLICY_ID = (
    "SWING-PHASE1-V1-RELATIVE-CONTEXT-POLICY"
)
SWING_V1_GAP_CONTEXT_POLICY_ID = "SWING-PHASE1-V1-GAP-CONTEXT-POLICY"
SWING_V1_PROBABLE_RECONCILIATION_POLICY_ID = (
    "SWING-PHASE1-V1-PROBABLE-RECONCILIATION-POLICY"
)
SWING_V1_LAYER1_POLICY_BUNDLE_ID = "SWING-PHASE1-V1-LAYER1-POLICY-BUNDLE"
KRONOS_V1_EVIDENCE_RETENTION_POLICY_CANDIDATE_ID = (
    "KRONOS-V1-EVIDENCE-RETENTION-POLICY-CANDIDATE"
)
IMPULSE_TIE_POLICY_REVIEW = "IMPULSE_TIE_POLICY_REVIEW"
SWING_V1_TRADINGVIEW_CONTEXT_POLICY_ID = (
    "SWING-PHASE1-V1-TRADINGVIEW-CONTEXT-POLICY"
)
SWING_V1_PRICE_BARRIER_POLICY_ID = "SWING-PHASE1-V1-PRICE-BARRIER-POLICY"
SWING_V1_OPTIONS_BARRIER_POLICY_ID = "SWING-PHASE1-V1-OPTIONS-BARRIER-POLICY"
SWING_V1_CLEAR_AIR_POLICY_ID = "SWING-PHASE1-V1-CLEAR-AIR-POLICY"
SWING_V1_READINESS_ASSESSMENT_POLICY_ID = (
    "SWING-PHASE1-V1-READINESS-ASSESSMENT-POLICY"
)
SWING_V1_LAYER2_V2_INTEGRATION_POLICY_ID = (
    "SWING-PHASE1-V1-LAYER2-V2-INTEGRATION-POLICY"
)

SWING_V1_LAYER1_POLICY_IDS = (
    SWING_V1_STRUCTURAL_DISCOVERY_POLICY_ID,
    SWING_V1_PROBABLE_FORMATION_POLICY_ID,
    SWING_V1_VOLUME_EVIDENCE_POLICY_ID,
    SWING_V1_CANDLE_EVIDENCE_POLICY_ID,
    SWING_V1_VOLATILITY_EVIDENCE_POLICY_ID,
    SWING_V1_FUTURES_POSITIONING_POLICY_ID,
    SWING_V1_IMPULSE_MATURITY_POLICY_ID,
    SWING_V1_RELATIVE_CONTEXT_POLICY_ID,
    SWING_V1_GAP_CONTEXT_POLICY_ID,
    SWING_V1_PROBABLE_RECONCILIATION_POLICY_ID,
)

__all__ = [
    "IMPULSE_TIE_POLICY_REVIEW",
    "KRONOS_V1_EVIDENCE_RETENTION_POLICY_CANDIDATE_ID",
    "SWING_V1_CANDLE_EVIDENCE_POLICY_ID",
    "SWING_V1_FUTURES_POSITIONING_POLICY_ID",
    "SWING_V1_GAP_CONTEXT_POLICY_ID",
    "SWING_V1_IMPULSE_MATURITY_POLICY_ID",
    "SWING_V1_LAYER1_POLICY_BUNDLE_ID",
    "SWING_V1_LAYER1_POLICY_IDS",
    "SWING_V1_LAYER2_V2_INTEGRATION_POLICY_ID",
    "SWING_V1_PROBABLE_FORMATION_POLICY_ID",
    "SWING_V1_PROBABLE_RECONCILIATION_POLICY_ID",
    "SWING_V1_TRADINGVIEW_CONTEXT_POLICY_ID",
    "SWING_V1_PRICE_BARRIER_POLICY_ID",
    "SWING_V1_OPTIONS_BARRIER_POLICY_ID",
    "SWING_V1_CLEAR_AIR_POLICY_ID",
    "SWING_V1_READINESS_ASSESSMENT_POLICY_ID",
    "SWING_V1_RELATIVE_CONTEXT_POLICY_ID",
    "SWING_V1_STRUCTURAL_DISCOVERY_POLICY_ID",
    "SWING_V1_VOLATILITY_EVIDENCE_POLICY_ID",
    "SWING_V1_VOLUME_EVIDENCE_POLICY_ID",
]
