"""Constructed Analyst observations, independent of gate expectations; no AI calls."""
from datetime import datetime, timedelta
from hashlib import sha256
import json
import pytest
from kronos.intraday.analyst_chart_observation import template, parse, FIELD, canonical
from kronos.intraday.chart_input import CORE_CONTENT, observation_bytes
from kronos.intraday.review_answer import parse_answer_pack, answer_artifact_bytes, answer_artifact_from_bytes
from kronos.intraday.review import ReviewError
from kronos.intraday.review_v2_transport import IntradayReviewV2Transport
from kronos.instrument.visual_identity_persistence import load_visual_identity_resolver
from .test_review_v2 import _application, _opening_inputs
from .test_visual_contract_v2 import nse_document
from .test_review import _png
from .chart_input_fixtures import configure_fixture_calendar

LABELS = (("NSE-EQ-ADANIGREEN", "Adani Green Energy Limited"),
          ("NSE-INDEX-BANKNIFTY", "Nifty Bank Index"))
# The synthetic chart scenario is predeclared here. It is not generated by the
# machine expectation function. Changing machine evidence must fail comparison.
ENDPOINTS = (("1D", "2026-08-27", "10:00", "16:30"),
             ("1H", "2026-08-27", "15:00", "16:00"),
             ("15M", "2026-08-28", "10:00", "10:15"),
             ("5M", "2026-08-28", "10:10", "10:15"))


def observed_panel(role, timeframe, subject, venue, day=None, start=None, end=None, currency=None, series=None):
    return dict(temporal_context=None, role=role, timeframe=timeframe, observed_subject=subject, venue=venue,
        observed_series=series, currency=currency, unit=None, trading_date=day,
        session=("REGULAR" if venue=="MCX" else "CONTINUOUS_TRADING") if day else None, timezone="Asia/Kolkata" if day else None,
        candle_start=f"{day}T{start}:00+05:30" if day else None,
        candle_end=f"{day}T{end}:00+05:30" if day else None,
        completion="COMPLETE" if day else None,
        captured_at="2026-08-28T10:16:00+05:30",
        latest_visible_end=f"{day}T{end}:00+05:30" if day else None,
        entire_panel_observed=True, opinion_overlays_present=False,
        content=[[key,"EXACT"] for key in CORE_CONTENT])


def fresh(tmp_path, symbol=LABELS[0][0], label=LABELS[0][1], *, payload=None):
    *_, mapping = _opening_inputs(subject=symbol)
    run, app = _application(tmp_path, mapping)
    app._clock=lambda: datetime.fromisoformat("2026-08-28T10:16:00+05:30")
    app._chart_input.clock=app._clock
    app._transport=IntradayReviewV2Transport(question_outbox=tmp_path/'questions', answer_inbox=tmp_path/'answers')
    app._visual_identity_resolver=load_visual_identity_resolver(publication_version="1.5.0")
    app._chart_input.resolver=app._visual_identity_resolver
    configure_fixture_calendar(app)
    cycle=app.create_eligible_cycles(run)[0]
    chart=app.upload_chart(cycle.cycle_identity, media_type="image/png", payload=_png(79) if payload is None else payload)
    assert app.review_store.load_chart_input(chart) is None
    result=app.create_individual_question_transport(cycle.cycle_identity)
    doc=json.loads(result.answer_template_path.read_bytes())
    answer=nse_document(result.packs[0]); answer['observed_visible_subject_identity']=label
    for item in answer['answers']:
        if item['question_id'] in {'Q6','Q9'}:
            item.update(observation_status="UNAVAILABLE",answer=None,visible_timeframes=[],visible_basis=None,
                        status_detail="No machine-selected single governed anchor.")
    answer['global_observation_status']='PARTIAL'
    header=template(result.packs[0])
    for row,(frame,day,start,end) in zip(header['panels'],ENDPOINTS,strict=True):
        row.update(panel_state="PRESENT",right_edge="EXACT",observed=observed_panel('NATIVE',frame,label,'NSE',day,start,end))
    answer[FIELD]=header;doc['candidates']=[answer]
    return app,cycle,chart,result,doc


def submit(app,cycle,result,doc):
    app._transport.answer_inbox.mkdir(exist_ok=True)
    (app._transport.answer_inbox/result.transport.expected_answer_filename).write_text(json.dumps(doc))
    return app.import_expected_answer(cycle.cycle_identity)


def snapshot(root):
    return {str(p.relative_to(root)):sha256(p.read_bytes()).hexdigest() for p in root.rglob('*') if p.is_file()}


@pytest.mark.parametrize('symbol,label',LABELS)
def test_fresh_sponsor_workflow_retains_receipt_and_replays(tmp_path,symbol,label):
    app,cycle,chart,result,doc=fresh(tmp_path,symbol,label)
    assert [p.suffix for p in app._transport.question_outbox.iterdir()]==['.pdf']
    assert app.review_store.load_chart_input(chart) is None
    # Read-only prevalidation itself creates no receipt or import.
    before=snapshot(app.review_store.root)
    assert app._prepare_transport_answer(result.transport,json.dumps(doc).encode()).validation.exact_match_count==1
    assert snapshot(app.review_store.root)==before
    outcome=submit(app,cycle,result,doc)
    assert (outcome.imported_count,outcome.rejected_count)==(1,0),outcome
    receipt=app.review_store.load_chart_input(chart)
    assert receipt.observation_source_identity.startswith('CHART-ANALYST-ANSWER-')
    evidence=app.review_store.load_visual_evidence_for_pack(result.packs[0].review_pack_identity)
    assert evidence.visual_identity_publication_version=='1.5.0'
    assert evidence.observed_visible_subject_identity==label
    parsed=parse_answer_pack(json.dumps(doc['candidates'][0]).encode())
    assert answer_artifact_from_bytes(answer_artifact_bytes(parsed))==parsed
    frozen=snapshot(app.review_store.root)
    assert submit(app,cycle,result,doc).already_imported_count==1
    assert snapshot(app.review_store.root)==frozen
    from kronos.intraday.review_v2_persistence import IntradayReviewV2Store
    restored=IntradayReviewV2Store(app.review_store.root)
    assert observation_bytes(restored.load_chart_input(chart))==observation_bytes(receipt)
    assert restored.load_visual_evidence_for_pack(evidence.review_pack_identity)==evidence


@pytest.mark.parametrize('mutation',[
    'subject','timeframe','missing','cropped_identity','cropped_time_axis','right_edge',
    'loading','unreadable','future','forming','wrong_revision','wrong_cycle','wrong_pack',
    'role_swap','no_endpoint','no_header','opinion','partial_panel','duplicate','unknown_key'])
def test_wrong_or_unprovable_answer_never_retains_receipt(tmp_path,mutation):
    app,cycle,chart,result,doc=fresh(tmp_path)
    answer=doc['candidates'][0];h=answer[FIELD];row=h['panels'][-1];p=row['observed']
    if mutation=='subject':p['observed_subject']='Nifty Bank Index'
    elif mutation=='timeframe':p['timeframe']='4H'
    elif mutation=='missing':row['panel_state']='ABSENT';p['timeframe']=None
    elif mutation.startswith('cropped_'):
        target='identity' if mutation=='cropped_identity' else 'time_axis'
        p['content']=[[k,'NOT_VISIBLE' if k==target else v] for k,v in p['content']]
    elif mutation=='right_edge':row['right_edge']='NOT_VISIBLE'
    elif mutation=='loading':row['panel_state']='LOADING'
    elif mutation=='unreadable':row['panel_state']='UNREADABLE'
    elif mutation=='future':p['latest_visible_end']='2026-08-28T10:20:00+05:30'
    elif mutation=='forming':p['completion']='INCOMPLETE'
    elif mutation=='wrong_revision':h['chart_binding_identity']='FOREIGN'
    elif mutation=='wrong_cycle':h['review_cycle_identity']='FOREIGN'
    elif mutation=='wrong_pack':h['review_pack_identity']='FOREIGN'
    elif mutation=='role_swap':p['role']='REFERENCE'
    elif mutation=='no_endpoint':p['candle_end']=None
    elif mutation=='no_header':answer.pop(FIELD)
    elif mutation=='opinion':p['opinion_overlays_present']=True
    elif mutation=='partial_panel':p['entire_panel_observed']=False
    elif mutation=='duplicate':h['panels'][-1]=h['panels'][0]
    else:p['expected_end']='COPY_FORBIDDEN'
    result_import=submit(app,cycle,result,doc)
    assert (result_import.imported_count,result_import.rejected_count)==(0,1),result_import
    assert app.review_store.load_chart_input(chart) is None
    assert app.review_store.load_visual_evidence_for_pack(result.packs[0].review_pack_identity) is None


def test_template_keeps_machine_orientation_out_of_observations(tmp_path):
    app,cycle,chart,result,doc=fresh(tmp_path)
    t=json.loads(result.answer_template_path.read_bytes())['candidates'][0][FIELD]
    assert parse(t)==canonical(t)
    for row in t['panels']:
        assert all(v is None for k,v in row['observed'].items() if k not in {'content','temporal_context'})
        assert all(v=='UNVERIFIABLE' for k,v in row['observed']['content'])
    from kronos.intraday.visual_review_pdf import answer_protocol
    protocol=' '.join(answer_protocol(paired=False))
    assert 'never from printed machine orientation' in protocol
    assert 'PARTIAL' in protocol and 'Q10' in protocol


def test_failed_receipt_persistence_cannot_publish_answer(tmp_path,monkeypatch):
    app,cycle,chart,result,doc=fresh(tmp_path)
    from kronos.intraday.review import ReviewFailure
    def fail(*args):raise ReviewError(ReviewFailure.INTEGRITY_INVALID)
    monkeypatch.setattr(app.review_store,'retain_chart_input',fail)
    outcome=submit(app,cycle,result,doc)
    assert outcome.imported_count==0
    assert app.review_store.load_visual_evidence_for_pack(result.packs[0].review_pack_identity) is None


def test_receipt_write_then_answer_failure_is_immutable_retryable(tmp_path,monkeypatch):
    app,cycle,chart,result,doc=fresh(tmp_path)
    from kronos.intraday.review import ReviewFailure
    original=app.review_store.retain_visual_evidence
    def fail(*args):raise ReviewError(ReviewFailure.INTEGRITY_INVALID)
    monkeypatch.setattr(app.review_store,'retain_visual_evidence',fail)
    assert submit(app,cycle,result,doc).imported_count==0
    retained=app.review_store.load_chart_input(chart)
    assert retained is not None
    assert app.review_store.load_visual_evidence_for_pack(result.packs[0].review_pack_identity) is None
    monkeypatch.setattr(app.review_store,'retain_visual_evidence',original)
    app._clock=lambda:datetime.fromisoformat('2026-08-28T10:17:00+05:30')
    assert submit(app,cycle,result,doc).imported_count==1
    assert app.review_store.load_chart_input(chart)==retained


from .test_review_v2_paired_generic import synthetic_commissioning


def fresh_mcx(tmp_path, family):
    from .test_mcx_asymmetric_correspondence import fixture
    app,cycle,chart,bundle,unused,result,rows=fixture(tmp_path,family,retain_observation=False)
    assert app.review_store.load_chart_input(chart) is None
    doc=json.loads((app._transport.answer_inbox/result.transport.expected_answer_filename).read_bytes())
    pack=app._paired.retained(cycle,chart)[3]
    h=template(pack,paired=True)
    # Fixed independent scenario, not copied from computed machine endpoints.
    native_ends=(('1D','2026-08-27','10:00','16:30'),('4H','2026-08-27','10:00','14:00'),
                 ('15M','2026-08-28','10:00','10:15'),('5M','2026-08-28','10:10','10:15'))
    ref=bundle.reference_relationship
    for i,row in enumerate(h['panels']):
        if i<4:
            obs=observed_panel('REFERENCE',('1D','4H','15M','5M')[i],
                ref.governed_visible_identity,ref.venue.value,currency='USD',series='TEST-LISTED-'+family)
        else:
            frame,day,start,end=native_ends[i-4]
            obs=observed_panel('NATIVE',frame,'TEST-EXACT-NATIVE-SERIES','MCX',day,start,end,currency='INR')
        row.update(panel_state='PRESENT',right_edge='EXACT',observed=obs)
    doc[FIELD]=h
    return app,cycle,chart,pack,result,doc


@pytest.mark.parametrize('family',['GOLDM','SILVERM','COPPER','CRUDE','NATGAS'])
def test_five_families_answer_is_observer_without_preexisting_receipt(tmp_path,synthetic_commissioning,family):
    app,cycle,chart,pack,result,doc=fresh_mcx(tmp_path,family)
    from kronos.intraday.analyst_chart_observation import receipt as prepare
    from kronos.intraday.review_mcx_paired_answer import parse_mcx_paired_answer
    prepared=prepare(parse_mcx_paired_answer(json.dumps(doc).encode()),pack,chart,app.review_store,imported_at=app._clock(),paired=True)
    comparisons=app._chart_input.evaluate(cycle,chart,bundle=app._paired.restore(cycle,chart)[0],resolver=app._paired.native_resolver,receipt=prepared)
    outcome=submit(app,cycle,result,doc)
    assert (outcome.imported_count,outcome.rejected_count)==(1,0),[(x.role,x.timeframe,x.overall,x.reasons) for x in comparisons]
    receipt=app.review_store.load_chart_input(chart)
    evidence=app._paired.retained_evidence(pack,chart)
    assert receipt.observation_source_identity.startswith('CHART-ANALYST-ANSWER-')
    assert evidence.reference_independent_correspondence=='NOT_INDEPENDENTLY_ESTABLISHED'
    assert evidence.reference_role=='SUPPORTING_VISUAL_CONTEXT_ONLY'
    assert evidence.reference_resolution is None
    assert evidence.reference_constituent_relationship=='NOT_ESTABLISHED'
    assert len(evidence.chart_correspondence)==8
    assert all(row[3]=='NOT_INDEPENDENTLY_ESTABLISHED' for row in evidence.chart_correspondence if row[0]=='REFERENCE')
    before=snapshot(app.review_store.root)
    assert submit(app,cycle,result,doc).already_imported_count==1
    assert snapshot(app.review_store.root)==before
    answer=app._paired.store.load_answer(evidence.answer_pack_identity)
    assert json.loads(answer.chart_observation_header)==doc[FIELD]


@pytest.mark.parametrize('mutation',['swap','wrong_contract','foreign_reference','future','missing','wrong_bundle'])
def test_mcx_observed_rows_fail_closed(tmp_path,synthetic_commissioning,mutation):
    app,cycle,chart,pack,result,doc=fresh_mcx(tmp_path,'CRUDE')
    h=doc[FIELD]
    if mutation=='swap':h['panels'][0]['observed'],h['panels'][4]['observed']=h['panels'][4]['observed'],h['panels'][0]['observed']
    elif mutation=='wrong_contract':h['panels'][4]['observed']['observed_subject']='CRUDEOILM2026'
    elif mutation=='foreign_reference':h['panels'][0]['observed']['observed_subject']='Natural Gas Futures'
    elif mutation=='future':h['panels'][1]['observed']['latest_visible_end']='2026-08-28T10:20:00+05:30'
    elif mutation=='missing':h['panels'][6]['panel_state']='ABSENT'
    else:h['chart_binding_identity']='FOREIGN'
    outcome=submit(app,cycle,result,doc)
    assert (outcome.imported_count,outcome.rejected_count)==(0,1),outcome
    assert app.review_store.load_chart_input(chart) is None


@pytest.mark.parametrize('mutation',['missing','tampered'])
def test_restoration_fails_closed_on_missing_or_corrupt_receipt(tmp_path,mutation):
    app,cycle,chart,result,doc=fresh(tmp_path)
    assert submit(app,cycle,result,doc).imported_count==1
    path=app.review_store.root/'chart-input-observations'/(chart.chart_revision_identity+'.json')
    if mutation=='missing':path.unlink()
    else:path.write_bytes(path.read_bytes().replace(b'Adani Green Energy Limited',b'Foreign'))
    with pytest.raises(ReviewError):
        app.review_store.load_visual_evidence_for_pack(result.packs[0].review_pack_identity)


def test_replacement_rejects_old_answer_without_backfill(tmp_path):
    app,cycle,chart,result,doc=fresh(tmp_path)
    old_bytes=app.review_store.load_chart_bytes(chart)
    newer=app.upload_chart(cycle.cycle_identity,media_type='image/png',payload=_png(80))
    assert newer.revision_ordinal==chart.revision_ordinal+1
    with pytest.raises(ReviewError):
        submit(app,cycle,result,doc)
    assert app.review_store.load_chart_input(chart) is None
    assert app.review_store.load_chart_input(newer) is None
    assert app.review_store.load_chart_bytes(chart)==old_bytes


def test_producer_advancement_between_prepare_and_persist_blocks_receipt(tmp_path):
    app,cycle,chart,result,doc=fresh(tmp_path)
    payload=json.dumps(doc).encode()
    prepared=app._prepare_transport_answer(result.transport,payload)
    assert prepared.validation.exact_match_count==1
    from .test_review_v2 import _retain_later_current_run
    _retain_later_current_run(app)
    final=app._persist_prepared_answer(prepared,payload)
    assert final.evidence==() and len(final.rejected)==1
    assert app.review_store.load_chart_input(chart) is None


def test_legacy_answer_bytes_and_question_semantics_unchanged(tmp_path):
    app,cycle,chart,result,doc=fresh(tmp_path)
    old=doc['candidates'][0];old.pop(FIELD)
    parsed=parse_answer_pack(json.dumps(old).encode())
    assert parsed.chart_observation_header is None
    assert FIELD not in json.loads(answer_artifact_bytes(parsed))['value']
    assert answer_artifact_from_bytes(answer_artifact_bytes(parsed))==parsed
    from kronos.intraday.visual_contract_v2 import VERSION
    assert VERSION=='2.0.0'


@pytest.mark.parametrize('mutation',['extra','version','duplicate_content','bad_bool','naive_time','bad_enum','missing_field'])
def test_header_schema_is_exact_and_conservative(tmp_path,mutation):
    app,cycle,chart,result,doc=fresh(tmp_path)
    h=doc['candidates'][0][FIELD];p=h['panels'][0]['observed']
    if mutation=='extra':h['confidence']=100
    elif mutation=='version':h['schema_version']='9.0.0'
    elif mutation=='duplicate_content':p['content'].append(p['content'][0])
    elif mutation=='bad_bool':p['entire_panel_observed']='true'
    elif mutation=='naive_time':p['candle_end']='2026-08-27T16:30:00'
    elif mutation=='bad_enum':p['content'][0][1]='VERIFIED'
    else:p.pop('opinion_overlays_present')
    with pytest.raises(ReviewError,match='SCHEMA_INVALID'):
        parse_answer_pack(json.dumps(doc['candidates'][0]).encode())


def test_exact_replay_after_producer_advance_and_conflict(tmp_path):
    app,cycle,chart,result,doc=fresh(tmp_path)
    payload=json.dumps(doc).encode()
    assert submit(app,cycle,result,doc).imported_count==1
    from .test_review_v2 import _retain_later_current_run
    _retain_later_current_run(app)
    before=snapshot(app.review_store.root)
    prepared=app._prepare_transport_answer(result.transport,payload)
    assert prepared.already_imported==(True,)
    assert app._persist_prepared_answer(prepared,payload).already_imported==(True,)
    assert snapshot(app.review_store.root)==before
    doc['candidates'][0]['answers'][0]['visible_basis']='Conflicting new observation.'
    rejected=app._prepare_transport_answer(result.transport,json.dumps(doc).encode())
    assert rejected.answers==() and rejected.rejected[0].reason.endswith('ANSWER_CONFLICT')
    assert snapshot(app.review_store.root)==before


def test_batch_header_members_are_independent_and_partial(tmp_path):
    from .test_review_v2_individual_inbox import _fixture,_cycles
    _,app=_fixture(tmp_path,('ADANIGREEN','M&M'),correspondence=False)
    resolver=load_visual_identity_resolver(publication_version='1.5.0')
    app._visual_identity_resolver=resolver;app._chart_input.resolver=resolver
    cycles=_cycles(app)
    for i,c in enumerate(cycles.values()):
        app.upload_chart(c.cycle_identity,media_type='image/png',payload=_png(90+i))
    result=app.create_combined_question_transport()
    doc=json.loads(result.answer_template_path.read_bytes())
    for i,(candidate,pack) in enumerate(zip(doc['candidates'],result.packs,strict=True)):
        label='Adani Green Energy Limited' if pack.expected_canonical_subject_identity=='NSE-EQ-ADANIGREEN' else 'Mahindra & Mahindra Ltd.'
        answer=nse_document(pack);answer['observed_visible_subject_identity']=label
        for q in answer['answers']:
            if q['question_id'] in {'Q6','Q9'}:q['answer']='NOT_OBSERVABLE'
        header=template(pack)
        for row,(frame,day,start,end) in zip(header['panels'],ENDPOINTS,strict=True):
            row.update(panel_state='PRESENT',right_edge='EXACT',observed=observed_panel('NATIVE',frame,label,'NSE',day,start,end))
        if i==1:header['panels'][-1]['right_edge']='UNVERIFIABLE'
        answer[FIELD]=header;doc['candidates'][i]=answer
    app._transport.answer_inbox.mkdir(exist_ok=True)
    (app._transport.answer_inbox/result.transport.expected_answer_filename).write_text(json.dumps(doc))
    outcome=app.import_all_expected_answers()
    assert (outcome.imported_count,outcome.rejected_count)==(1,1),outcome
    for i,pack in enumerate(result.packs):
        retained=app.review_store.load_chart_input(app.review_store.load_chart(pack.chart_revision_identity))
        assert (retained is not None)==(i==0)
